# Generated by Django 6.0.3 on 2026-04-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followerscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followerscount',
            old_name='follow',
            new_name='follower',
        ),
    ]
